# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Greeting' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'

  # Pods for Greeting

  target 'GreetingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'iosApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp

  target 'iosAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
